import Tailor
import TailorTesting
import XCTest

typealias NSRegularExpression=Tailor.NSRegularExpression

prepareTestSuite()

XCTMain([
  TestAesEncryptor(),
  TestApplication(),
  TestAuthenticationFilter(),
  TestCacheImplementation(),
  TestCollectionType(),
  TestConnection(),
  TestControllerType(),
  TestCookieJar(),
  TestCookie(),
  TestCsrfFilter(),
  TestDatabaseRow(),
  TestDatabaseDriver(),
  TestDatabaseLocalization(),
  TestDatabaseValue(),
  TestDictionary(),
  TestEmail(),
  TestEmailAgent(),
  TestEtagFilter(),
  TestExternalProcess(),
  TestFileEmailAgent(),
  TestHttpMessageType(),
  TestJobSchedulingTaskType(),
  TestLocalizationSource(),
  TestMemoryCacheStore(),
  TestMemoryEmailAgent(),
  TestNSData(),
  TestNSRegularExpression(),
  TestPasswordHasherType(),
  TestPropertyListLocalization(),
  TestRandomNumber(),
  TestRequest(),
  TestRequestFilterType(),
  TestResponse(),
  TestRouteSet(),
  TestShaPasswordHasher(),
  TestSeedTaskType(),
  TestSession(),
  TestSerializableValue(),
  TestSmtpEmailAgent(),
  TestString(),
  TestTailorTestable(),
  TestTemplateTestable(),
  TestTimestamp(),
  TestTypeInventory(),
  TestUserType(),
])