import Tailor
import TailorTesting
import XCTest

typealias NSRegularExpression=Tailor.NSRegularExpression

prepareTestSuite()

XCTMain([
  TestAesEncryptor(),
  TestAlterationScript(),
  TestAlterationsTask(),
  TestApplication(),
  TestAuthenticationFilter(),
  TestCacheImplementation(),
  TestCollectionType(),
  TestConnection(),
  TestControllerType(),
  TestCookieJar(),
  TestCookie(),
  TestCsrfFilter(),
  TestCsvParser(),
  TestDatabaseRow(),
  TestDatabaseDriver(),
  TestDatabaseLocalization(),
  TestDatabaseValue(),
  TestDictionary(),
  TestEmail(),
  TestEmailAgent(),
  TestEtagFilter(),
  TestExternalProcess(),
  TestFileEmailAgent(),
  TestHttpMessageType(),
  TestJobSchedulingTaskType(),
  TestJsonConvertible(),
  TestJsonError(),
  TestJsonPrimitive(),
  TestLocalizationSource(),
  TestMemoryCacheStore(),
  TestMemoryEmailAgent(),
  TestModel(),
  TestNSData(),
  TestNSRegularExpression(),
  TestPaginatedList(),
  TestPasswordHasherType(),
  TestPersistable(),
  TestPersistableEnum(),
  TestPropertyListLocalization(),
  TestQuery(),
  TestRandomNumber(),
  TestRequest(),
  TestRequestFilterType(),
  TestResponse(),
  TestRouteSet(),
  TestShaPasswordHasher(),
  TestSeedTaskType(),
  TestSession(),
  TestSerializableValue(),
  TestSerializationConversions(),
  TestSerializationError(),
  TestSmtpEmailAgent(),
  TestString(),
  TestTailorTestable(),
  TestTask(),
  TestTemplateTestable(),
  TestTimestamp(),
  TestTypeInventory(),
  TestUserType(),
  TestValidation(),
  TestValidationError(),
])
